name: Push to PWS

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**.md'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - '**.md'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set up Git
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'

    - name: Debug Git Information
      run: |
        echo "Git status:"
        git status
        echo "Git remote -v:"
        git remote -v
        echo "Git branch:"
        git branch -a
        echo "Git log:"
        git log --oneline --decorate --graph --all

    - name: Push to PWS
      env:
        PWS_URL: ${{ secrets.PWS_URL }}
      run: |
        # Check if main branch exists locally
        if ! git show-ref --verify --quiet refs/heads/main; then
          echo "Creating main branch"
          git branch main
        fi

        # Switch to main branch
        git checkout main

        # Ensure that the local branch is up-to-date
        git pull origin main

        # Push to PWS and capture the output
        echo "Pushing to PWS..."
        push_output=$(git push $PWS_URL main:main 2>&1)
        echo "$push_output"
        if [[ $? -ne 0 ]]; then
          echo "Push failed with output: $push_output"
          echo "Error: Unable to push changes. Please check the error message above and resolve any conflicts manually."
          exit 1
        fi
        echo "Push successful with output: $push_output"
